services:
  db:
    container_name: database
    image: postgres
    restart: always
    ports:
      - ${port_db}:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: ${pg_pass}
      POSTGRES_DB: ${pg_db}

  panel:
    container_name: admin_panel
    image: adminer
    restart: always
    ports:
      - ${port_panel}:8080

  app:
    container_name: app
    build:
      dockerfile: app.dockerfile
    ports:
      - ${port_app}:80
    depends_on:
      db:
        condition: service_healthy
